# fly.toml app configuration file generated for global-latency-tracker-probe-jnb on 2026-05-31T23:02:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'global-latency-tracker-probe-jnb'
primary_region = 'jnb'

[build]
  dockerfile = 'deploy/Dockerfile.probe'

[env]
  HUB_URL = 'https://global-latency-tracker.onrender.com'
  PROBE_INTERVAL = '60s'
  PROBE_REGION = 'Africa'
  PROBE_TARGET_URL = 'https://api.spacexdata.com/v4/launches'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
