app = 'global-latency-tracker-probe-gru'
primary_region = 'gru'

[build]
  dockerfile = '../Dockerfile.probe'

[env]
  HUB_URL = 'https://global-latency-tracker.onrender.com'
  PROBE_INTERVAL = '60s'
  PROBE_REGION = 'South America'
  PROBE_TARGET_URL = 'https://www.ethz.ch'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
