app = 'global-latency-tracker-probe-lax'
primary_region = 'lax'

[build]
  dockerfile = '../Dockerfile.probe'

[env]
  HUB_URL = 'https://global-latency-tracker.onrender.com'
  PROBE_INTERVAL = '60s'
  PROBE_REGION = 'US-West'
  PROBE_TARGET_URL = 'https://api.spacexdata.com/v4/launches'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
